[book]
authors = ["liu <liu_fanyi@hotmail.com>"]
language = "zh"
multilingual = false
src = "src"
title = "匪帮群评"

[preprocessor.theme]
pagetoc = true
sidebar-width = "250px"

[output.html]
default-theme = "ayu"
git-repository-url = ""
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true

[output.html.print]
enable = false